name: Integracion Continua (CI)

# Esto define CUÁNDO se ejecuta el robot (al hacer push a la rama main)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  construir_y_probar:
    runs-on: ubuntu-latest # El sistema operativo del servidor temporal de GitHub

    steps:
    # Paso 1: Copiar tu código al servidor temporal
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    # Paso 2: Instalar Python
    - name: Configurar Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Paso 3: Instalar las dependencias de tu proyecto
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt

    # Paso 4: Validar que el entorno funciona (un test sencillo para que pase en verde)
    - name: Validar importación de FastAPI
      run: |
        python -c "import fastapi; print('FastAPI se instaló e importó con éxito')"